config/routes.rb
Rails.application.routes.draw do
  resources :topics
  get 'home/index'

  get 'home/authentication'

  get 'home/index'

  get 'home/authentication'

  devise_for :users
  resources :teachers
  resources :lectures
  resources :exams
  resources :users
  root "home#index"

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :teach_relations, dependent: :destroy
  has_many :teachers, through: :teach_relations

  has_many :exam_relations, dependent: :destroy
  has_many :exams, through: :exam_relations
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]
  # GET /lectures
  # GET /lectures.json
  def index
    @teacher = Teacher.new
    @search_form = LectureSearchForm.new(params[:search])
    @lectures = @search_form.search
    @lectures = Lecture.all if @lectures == Lecture

  end

  class LectureSearchForm
    include ActiveModel::Model
    attr_accessor :lecture_name
    def search
      rel = Lecture
      rel = rel.where("name like '%" +lecture_name+ "%'") if lecture_name.present?
      rel
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @exams = Exam.where(lecture_id: @lecture)
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:name, :teacher_id, :year, :gakubu, :gakka, :term, :lec_type)
    end

end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :gakubu %><br>
    <%= f.number_field :gakubu %>
  </div>
  <div class="field">
    <%= f.label :gakka %><br>
    <%= f.number_field :gakka %>
  </div>
  <div class="field">
    <div class="field">
      <label for="term">開講ターム</label>(1,2ターム連続の場合は1ターム扱い)<br>
      <select id="term" name="lecture[term]">
        <option value="1" selected>第１ターム</option>
        <option value="2">第２ターム</option>
        <option value="3">第３ターム</option>
        <option value="4">第４ターム</option>
        <option value="0">その他</option>
      </select>
    </div>
  </div>
  <div class="field">
    <%= f.label :lec_type %><br>
    <%= f.number_field :lec_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="conteiner">
  <h1>講義検索</h1>
  <!-- 検索フォームの追加 -->
  <%= form_for @search_form, as: 'search', url: :lectures, html: {method: :get} do |f| %>
  <%= f.label :lecture_name, "講義名" %>
  <%= f.text_field :lecture_name %>
  <%= f.submit "検索" %>
  <% end %><br>
  <!-- ここまで -->
</div>


<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>講義名</th>
      <th>担当教員</th>
      <th>開講学部</th>
      <th>学科</th>
      <th>施行ターム</th>
      <th>分類</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
    <% @teacher = Teacher.find(lecture.teacher_id) %>
      <tr>
        <td><%= link_to lecture.name, lecture %></td>
        <td><%= link_to @teacher.name, @teacher %></td>
        <td><%= GakubuList.find(lecture.gakubu).name %></td>
        <td><%= GakkaList.find(lecture.gakka).name %></td>
        <td><%if lecture.term == 0%>その他<%else%>第<%= lecture.term %>ターム<%end%></td>
        <td><%  if lecture.lec_type == 1 %>必修<%else%>基盤<%end%></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>


<h1>講義情報</h1>
<p>
<strong>講義名:</strong>
<%= @lecture.name %>
</p>
<p>
  <strong>担当教員:</strong>
  <%= link_to Teacher.find(@lecture.teacher_id).name, '/teachers/'+@lecture.teacher_id.to_s %>
</p>

<p>
  <strong>Gakubu:</strong>
  <%= GakubuList.find(@lecture.gakubu).name %>
</p>

<p>
  <strong>Gakka:</strong>
  <%= GakkaList.find(@lecture.gakka).name %>
</p>

<p>
  <strong>Term:</strong>
  第<%= @lecture.term %>ターム
</p>

<p>
  <strong>Type:</strong>
  <%  if @lecture.lec_type == 1 %>必修<%else%>基盤<%end%>
</p>

<hr>
<h1>投稿された過去問</h1>
<% unless current_user %><strong>
  <font color = "red"><strong>過去問を見るには<%= link_to "ログイン", new_user_session_url %>が必要です</strong></font>
</strong><% end %>
<!-- exams/showへのリンク -->
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>ファイル名</th>
      <th>投稿者</th>
      <th>実施年度</th>
      <th>区分</th>
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam|  %>
      <tr>
        <td><%= link_to exam.name, exam.image.url %></td>
        <td><%if current_user%><%= link_to User.find(exam.user_id).name, user_path(exam.user_id) %><%else%><%=User.find(exam.user_id).name%><%end%></td>
        <td><%= exam.year %></td>
        <td><%  if exam.season == 0 %>中間<%elsif exam.season == 1%>期末<%else%>その他<%end%> </td>

        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Exam', new_exam_path(@lecture) %>

<!-- ここまで -->

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>