config/routes.rb
Rails.application.routes.draw do
  resources :topics
  get 'home/index'

  get 'home/authentication'

  get 'home/index'

  get 'home/authentication'

  devise_for :users
  resources :teachers
  resources :lectures
  resources :exams
  resources :users
  root "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :year, presence: true


  has_many :posting_relations, dependent: :destroy
  has_many :exam, through: :posting_relations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @exams = Exam.where(user_id: @user)
    @exams = Exam.all if @exams == Exam
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :mail, :year, :gakubu, :gakka)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :gakubu %><br>
    <%= f.select :name, GakubuList.all.map{|b| [b.name, b.id]} %>
    <%= f.number_field :gakubu %>
  </div>
  <div class="field">
    <%= f.label :gakka %><br>
    <%= f.number_field :gakka %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Year</th>
      <th>Gakubu</th>
      <th>Gakka</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.year %></td>
        <td><%= user.gakubu %></td>
        <td><%= user.gakka %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %>さん</h1>
<p><%= @user.year %>年度　入学</p>


<h2>投稿した過去問データ</h2>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>講義名</th>
      <th>ラベル名</th>
      <th>開講学部</th>
      <th>施行ターム</th>
      <th>分類</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
    <tr>
      <td><%= link_to Lecture.find(exam.lecture_id).name, Lecture.find(exam.lecture_id) %></td>
      <td><%= link_to "閲覧", exam.image.url %></td>
      <td><%= GakubuList.find(Lecture.find(exam.lecture_id).gakubu).name %></td>
      <td><%if Lecture.find(exam.lecture_id).term == 0%>その他<%else%>第<%= Lecture.find(exam.lecture_id).term %>ターム<%end%></td>
      <td><%  if Lecture.find(exam.lecture_id).lec_type == 1 %>必修<%else%>基盤<%end%></td>
      <td><%= link_to 'Edit', edit_lecture_path(Lecture.find(exam.lecture_id)) %></td>
      <td><%= link_to 'Destroy', Lecture.find(exam.lecture_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>