config/routes.rb
Rails.application.routes.draw do
  resources :topics
  get 'home/index'

  get 'home/authentication'

  get 'home/index'

  get 'home/authentication'

  devise_for :users
  resources :teachers
  resources :lectures
  resources :exams
  resources :users
  root "home#index"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :teach_relations, dependent: :destroy
  has_many :lectures, through: :teach_relations

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @search_form = TeacherSearchForm.new(params[:search])
    @teachers = @search_form.search
    @teachers = Teacher.all if @teachers == Teacher
  end

  class TeacherSearchForm
    include ActiveModel::Model
    attr_accessor :teacher_name
    def search
      rel = Teacher
      rel = rel.where("name like '%" +teacher_name+ "%'") if teacher_name.present?
      rel
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  #  @lectures = Lecture.all
    @lectures = Lecture.where(teacher_id: @teacher)
    @lectures = Lecture.all if @lectures == Lecture
  end


  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :lecture_id, :gakubu, :gakka)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gakubu %><br>
    <%= f.number_field :gakubu %>
  </div>
  <div class="field">
    <%= f.label :gakka %><br>
    <%= f.number_field :gakka %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<!-- 検索フォームの追加 -->
<%= form_for @search_form, as: 'search', url: :teachers, html: {method: :get} do |f| %>
<%= f.label :teacher_name, "教員名" %>
<%= f.text_field :teacher_name %>
<%= f.submit "検索" %>
<% end %><br>
<!-- ここまで -->


<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>教員名</th>
      <th>所属学部</th>
      <th>所属学科</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to teacher.name, teacher %></td>
        <td><%= GakubuList.find(teacher.gakubu).name %></td>
        <td><%= GakkaList.find(teacher.gakka).name %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Lecture:</strong>
  <%= @teacher.lecture_id %>
</p>

<p>
  <strong>Gakubu:</strong>
    <%= GakubuList.find(@teacher.gakubu).name %>
</p>

<p>
  <strong>Gakka:</strong>
    <%= GakkaList.find(@teacher.gakka).name %>
</p>
<hr>

<h1>担当講義一覧</h1><br>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>講義名</th>
      <th>開講学部</th>
      <th>施行ターム</th>
      <th>分類</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
    <tr>
        <td><%= link_to lecture.name, lecture %></td>
        <td><%= GakubuList.find(lecture.gakubu).name %></td>
        <td><%if lecture.term == 0%>その他<%else%>第<%= lecture.term %>ターム<%end%></td>
        <td><%  if lecture.lec_type == 1 %>必修<%else%>基盤<%end%></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>